package controlador;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class altaController {

	// Event Listener on Button.onAction
	@FXML
	public void handleButtonAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
